config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "songs#index"

  resources :songs, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    if params[:q].present?
      @songs = Song.where('title ILIKE ?', "%#{params[:q]}%")
    else
      @songs = Song.all
    end

    if turbo_frame_request?
      render partial: "songs", locals: { songs: @songs }
    else
      render :index
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Buscador de video-aulas de acordeon da fisarmonica.online</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" href="https://fisarmonica.online/wp-content/uploads/2021/08/cropped-logo_icon-1-32x32.png" sizes="32x32" />
    <link rel="icon" href="https://fisarmonica.online/wp-content/uploads/2021/08/cropped-logo_icon-1-192x192.png" sizes="192x192" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-800">
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/songs/_song.html.erb
<div id="<%= dom_id song %>">
  <p class="text-lg leading-loose">
    <%= link_to song.title, song.link, target: "_blank", class: "text-orange-600 underline hover:text-orange-700" %>
  </p>
</div>

app/views/songs/_songs.html.erb
<%= turbo_frame_tag "songs" do %>
  <%= render songs %>
<% end %>

app/views/songs/index.html.erb
<a target="_blank" href="https://github.com/fernand-o/fisarmonica" class="fixed top-0 right-0 flex items-center bg-gray-800 text-white py-2 px-4 m-4 rounded-lg">
  <%= image_tag("github-mark-white.png", alt: "Project Link", class:"w-4 h-4 mr-2") %>
  <span>Link do projeto</span>
</a>

<div class="flex-col">
  <span class="text-2xl text-white">Repertório de vídeo-aulas de acordeon da Fisarmonica.online</span>
  <br>
  <span class="text-white">Aviso: Esse site apenas possibilita uma busca mais fácil das video aulas da fisarmonica.com.br, todos os links aqui enviam para a plataforma. Você precisa estar logado para acessá-los.</span>
  <br>
  <br>
  <%= form_with(url: songs_path, method: :get, data: { controller: "search-form", turbo_frame: "songs", turbo_action: "advance" }) do |form| %>
    <%= form.label :query, "Buscar por música ou artista:", class: "block mb-2 text-white" %>
    <div class="flex space-x-3">
      <%= form.text_field :q, 
        value: params[:q],
        data: { action: "input->search-form#search" },
        class: "py-3 px-4 rounded border ring-0 focus:ring-4 focus:ring-orange-100 focus:shadow-none focus:border-orange-500 focus:outline-none bg-gray-300" %>

      <%= form.submit 'Buscar', class: "px-4 py-3 font-medium
    bg-orange-300 text-neutal-900 rounded flex items-center cursor-pointer hover:bg-orange-400 focus:ring-4 ring-0 focus:ring-orange-100" %>
    </div>
  <% end %>

  <div class="my-6">
    <%= render "songs", songs: @songs %>
  </div>
</div>